law/urls.py
from django.contrib import admin # type: ignore
from django.urls import path, include # type: ignore
from django.conf import settings # type: ignore
from django.conf.urls.static import static # type: ignore



urlpatterns = [
    path('admin/', admin.site.urls),
    path('step1/', include("step1.urls")),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls'))
  
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

step1/urls.py
from django.urls import path # type: ignore
from . import views


app_name= "step1"

urlpatterns = [
    path("", views.index, name="index"),
    path("events", views.all_events, name="event_list"),
    path("add_venue", views.add_venue, name="add_venue"),
    path("list_venue", views.list_venue, name="list_venue"),
    path("show_venue/<venue_id>", views.show_venue, name="show_venue"),
    path("search_venues", views.search_venues, name="search_venues"),
    path("update_venue/<venue_id>", views.update_venue, name="update_venue"),
    path("update_event/<venue_id>", views.update_event, name="update_event"),
    path("add_event", views.add_event, name="add_event"),
    path("delete_event/<event_id>", views.delete_event, name="delete_event"),
    path("delete_venue/<venue_id>", views.delete_venue, name="delete_venue"),
    path("venue_text", views.venue_text, name="venue_text"),
    path("venue_csv", views.venue_csv, name="venue_csv"),
    path("venue_pdf", views.venue_pdf, name="venue_pdf"),
    path("my_events", views.my_events, name="my_events"),
    path("search_events", views.search_events, name="search_events"),
    path("admin_approvel", views.admin_approvel, name="admin_approvel")
]

step1/models.py
from django.db import models # type: ignore
from django.contrib.auth.models import User # type: ignore
from datetime import date
# Create your models here.







class Venue(models.Model):
    name = models.CharField('Venue Name', max_length=120)
    address = models.CharField(max_length=300)
    zip_code =models.CharField('Zip Code', max_length=15)
    phone = models.CharField('Contact Phone', max_length=25, blank=True)
    web = models.URLField('Website Address', blank=True)
    email_address = models.EmailField('Email Address', blank=True)
    owner = models.IntegerField("Venue Owner", blank=False, default=1)
    venue_image = models.ImageField(null=True, blank=True, upload_to="images/")
    
    

    def __str__(self):
            return self.name




class MyclubUser(models.Model):
    
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField('User Email')
    
    def __str__(self):
            return self.first_name + ' ' + self.last_name


class Event(models.Model):
    
    name = models.CharField('Event Name', max_length=120)
    event_date = models.DateTimeField('Event_date')
    venue = models.ForeignKey(Venue, blank=True, null=True, on_delete=models.CASCADE)
    #venue = models.CharField(max_length=120)
    manager = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL)
    description = models.TextField(blank=True)
    attendees = models.ManyToManyField(MyclubUser, blank=True)
    approved = models.BooleanField('Approved', default=False)
    
    

    def __str__(self):
        return self.name
    
    @property
    def Days_till(self):
        today = date.today()
        days_till = self.event_date.date() - today
        days_till_stripped = str(days_till).split(",",1)[0]
        return days_till_stripped
        
    
    
    
    
     

step1/forms.py
from django import forms # type: ignore
from django.forms import ModelForm # type: ignore
from .models import Venue, Event # type: ignore



# User Event Form

class EventForm(ModelForm):
    class  Meta:
        model = Event
        fields = ('name', 'event_date', 'venue', 'attendees', 'description',)
        
        labels ={
            'name': '',
            'event_date':'YYYY-MM-DD HH:MM:SS',
            'venue':'Venue',
            'attendees':'Attendees',
            'description':'',
        }
        
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Venue Name'}),
            'event_date':forms.TextInput(attrs={'class': 'form-control', 'placeholder':'event_date'}),
            'venue':forms.Select(attrs={'class': 'form-select', 'placeholder':'venue'}),
            'attendees':forms.SelectMultiple(attrs={'class': 'form-control', 'placeholder':'attendees'}),
            'description':forms.Textarea(attrs={'class': 'form-control','placeholder':'description'}),
        }


#Admin SuperUser Event Form


class EventFormAdmin(ModelForm):
    class  Meta:
        model = Event
        fields = ('name', 'event_date', 'venue', 'manager', 'attendees', 'description',)
        
        labels ={
            'name': '',
            'event_date':'YYYY-MM-DD HH:MM:SS',
            'venue':'Venue',
            'manager':'Manager',
            'attendees':'Attendees',
            'description':'',
        }
        
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Venue Name'}),
            'event_date':forms.TextInput(attrs={'class': 'form-control', 'placeholder':'event_date'}),
            'venue':forms.Select(attrs={'class': 'form-select', 'placeholder':'venue'}),
            'manager':forms.Select(attrs={'class': 'form-select', 'placeholder':'manager'}),
            'attendees':forms.SelectMultiple(attrs={'class': 'form-control', 'placeholder':'attendees'}),
            'description':forms.Textarea(attrs={'class': 'form-control','placeholder':'description'}),
        }







class VenueForm(ModelForm):
    class  Meta:
        model = Venue
        fields = ('name', 'address', 'zip_code', 'phone', 'web', 'email_address', 'venue_image')
        
        labels ={
            'name': '',
            'address':'',
            'zip_code':'',
            'phone':'',
            'web':'',
            'email_address':'',
            'venue_image': '',
        }
        
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Venue Name'}),
            'address':forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Address'}),
            'zip_code':forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Zip code'}),
            'phone':forms.TextInput(attrs={'class': 'form-control', 'placeholder':'phone'}),
            'web':forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Web Address'}),
            'email_address':forms.EmailInput(attrs={'class': 'form-control','placeholder':'Email'}),
        }

step1/views.py
from django.shortcuts import render, redirect # type: ignore
import calendar
from datetime import datetime
from django.http import HttpResponseRedirect # type: ignore
from calendar import HTMLCalendar
from .models import Event, Venue
from .forms import VenueForm, EventForm, EventFormAdmin
from django.http import HttpResponse # type: ignore
import csv
from django.http import FileResponse # type: ignore
import io
from reportlab.pdfgen import canvas # type: ignore
from reportlab.lib.units import inch # type: ignore
from reportlab.lib.pagesizes import letter # type: ignore
from django.contrib import messages # type: ignore
from django.contrib.auth.models import User # type: ignore


# Create your views here.


from django.core.paginator import Paginator # type: ignore



def admin_approvel(request):
    event_list = Event.objects.all().order_by("-event_date")
    event_count = Event.objects.all().count()
    venue_count = Venue.objects.all().count()
    user_count = User.objects.all().count()
    if request.user.is_superuser:
        if request.method == "POST":
            id_list = request.POST.getlist('boxes')
            event_list.update(approved=False)
            for x in id_list:
                Event.objects.filter(pk=int(x)).update(approved=True)
                
            messages.success(request, "Event list Approvel")
            return redirect('step1:event_list')
        else:
            return render(request, "step1/admin_approval.html",{
                "event_list" : event_list,
                "event_count": event_count,
                "venue_count": venue_count,
                "user_count" : user_count
            })
    else:
        messages.success(request, "You are not authorized to use this page.")
        return redirect('step1:index') 
    
  
    





def my_events(request):
    
    
    
    if request.user.is_authenticated:
       
        me = request.user.id
        events = Event.objects.filter( attendees=me)
        return render(request, "step1/my_events.html",{
            "events": events,
            
        })
        
    else:
        messages.success(request, ("You Aren't authorized to view this page"))
        return redirect('step1:event_list')




def venue_pdf(request):
    
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=letter, bottomup=0)
    textob = c.beginText()
    textob.setTextOrigin(inch, inch)
    textob.setFont("Helvetica", 14)
    
    venues = Venue.objects.all()
    lines = []
    
    
    for venue in venues:
        lines.append(venue.name)
        lines.append(venue.address)
        lines.append(venue.phone)
        lines.append(venue.web)
        lines.append(venue.email_address)
        lines.append("  ")
       

    for line in lines:
        textob.textLine(line)
        

    c.drawText(textob)
    c.showPage()
    c.save()
    buf.seek(0)
    
    return FileResponse(buf, as_attachment=True, filename='venue.pdf')





def venue_csv(request):
    
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename=venues.csv'
    
    writer = csv.writer(response)
    
    
    venues = Venue.objects.all()
    

    writer.writerow(['Venue Name', 'Address', 'Zip Code', 'Phone', 'Web Address', 'Email'])


    
    for venue in venues:
        writer.writerow([venue.name, venue.address, venue.phone, venue.web, venue.email_address])
        

  
    return response






def venue_text(request):
    
    response = HttpResponse(content_type='text/plain')
    response['Content-Disposition'] = 'attachment; filename=venues.txt'
    
    venues = Venue.objects.all()
    
    lines = []
    
    for venue in venues:
        lines.append(f'{venue.name}\n{venue.address}\n{venue.phone}\n\n\n')
        

    response.writelines(lines)
    return response



def delete_venue(request, venue_id):
    
       
        venue = Venue.objects.get(pk=venue_id)
        venue.delete()
        return redirect('step1:list_venue')





def delete_event(request, event_id):
    
       event = Event.objects.get(pk=event_id)
       if request.user == event.manager:
            event.delete()
            messages.success(request, ("Event Deleted!"))
            return redirect('step1:event_list')
       else:
           messages.success(request, ("You are not Authorized to delete this event"))
           return redirect('step1:event_list')

    


def add_event(request):
    submitted = False
    if request.method == "POST":
        if request.user.is_superuser:
            form = EventFormAdmin(request.POST)
            if form.is_valid():
                    form.save()
                    return HttpResponseRedirect('add_event?submitted=True')
        
            
            
        else: 
            form = EventForm(request.POST)
            event = form.save(commit=False)
            event.manager = request.user
            event.save
           
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('add_event?submitted=True')
    else:
        
        if request.user.is_superuser:
                form = EventFormAdmin
        else:
             form = EventForm
        if "submitted" in request.GET:
            submitted = True
   
    return render(request, "step1/add_event.html",{
        "form": form,
        "submitted": submitted
    })



def update_event(request, venue_id):
    
        event = Event.objects.get(pk=venue_id)
        if request.user.is_superuser:
            form = EventFormAdmin(request.POST or None, instance=event)
          
        else:    
            form = EventForm(request.POST or None, instance=event)
        if form.is_valid():
            form.save()
            return redirect('step1:event_list')
        return render(request, "step1/update_event.html",{
            "venue": event,
            "form": form
        })
    



def update_venue(request, venue_id):
    
        venue = Venue.objects.get(pk=venue_id)
        form = VenueForm(request.POST or None, request.FILES or None, instance=venue)
        if form.is_valid():
            form.save()
            return redirect('step1:list_venue')
        return render(request, "step1/update_venue.html",{
            "venue": venue,
            "form": form
        })
    


def search_venues(request):


    
    if request.method == "POST":
        searched = request.POST["searched"]
        Venues = Venue.objects.filter(name__contains=searched)
    
        return render(request, "step1/search_venues.html",{
           "searched": searched,
           "Venues": Venues
        })
        
    else:
        
        
        return render(request, "step1/search_venues.html",{
            
        
            })


def search_events(request):
    
    if request.method == "POST":
        searched = request.POST["searched"]
        events = Event.objects.filter(name__contains=searched)
    
        return render(request, "step1/search_events.html",{
           "searched": searched,
           "events": events
        })
        
    else:
        
        
        return render(request, "step1/search_events.html",{
            
        
            })



def show_venue(request, venue_id):
    venue = Venue.objects.get(pk=venue_id)
    venue_owner = User.objects.get(pk=venue.owner)
    return render(request, "step1/show_venue.html",{
            "venue": venue,
            "venue_owner": venue_owner
        })



def list_venue(request):
      venue_list = Venue.objects.all()
      p = Paginator(Venue.objects.all(), 9)
      page = request.GET.get('page')
      venues = p.get_page(page)
      nums = "a" * venues.paginator.num_pages
      return render(request, "step1/venues.html",{
            "venue_list": venue_list,
            "venues" : venues,
            "nums": nums
        })
    






def add_venue(request):
    submitted = False
    if request.method == "POST":
       
        form = VenueForm(request.POST, request.FILES)
      
        if form.is_valid():
                venue = form.save(commit=False)
                venue.owner = request.user.id
                venue.save()
                return HttpResponseRedirect('add_venue?submitted=True')
    else:
        form = VenueForm       
            
        if "submitted" in request.GET:
            submitted = True
   
    return render(request, "step1/add_venue.html",{
        "form": form,
        "submitted": submitted
    })



def all_events(request):
    event_list = Event.objects.all().order_by('-event_date')
    return render(request, "step1/event_list.html",{
        "event_list":event_list
    })






def index(request, year=datetime.now().year, month=datetime.now().strftime('%B')):
    month = month.capitalize()
    month_number = list(calendar.month_name).index(month)
    month_number = int(month_number)
    
    cal = HTMLCalendar().formatmonth(year,month_number)
   
    
    event_list = Event.objects.filter(
        event_date__year = year,
        event_date__month= month_number,
    ) 
    
    
    
    return render(request, "step1/index.html",{
        "year":year,
        "month":month,
        "month_number":month_number,
        "cal":cal,
        "event_list": event_list,
    })

step1/templates/step1/add_event.html

{% extends 'step1/layout.html' %}


{% block body %}

<br/>

{% if user.is_authenticated %}

    <center>

    {{ user.id }}

            <h1>Add Event To Database</h1>
    </center>
            <br/><br/>
            {% if submitted %}

                <h1>Your Event Was Submitted Successfully!!</h1>

            {% else %}

        
                
                <form action="" method=POST>
                    {% csrf_token %}

                    {{ form.as_p }}


                    <br/>
                    <input type="submit" value="Submit" class="btn btn-success">
                <form>
                
            
            {% endif %}
 
   
   
{% else %}

    <h1>Sorry you must be logined </h1>

    <a href="{% url 'login_user'%}">Login</a>
   
{% endif %}  
    
{% endblock %}



step1/templates/step1/add_venue.html
{% extends 'step1/layout.html' %}



{% block body %}





{% if user.is_authenticated %}

    <center>

    {{ user.id}}

        <h1>Add Venue To Database</h1>

        <br/><br/>
        {% if submitted %}

            <h1>Your Venue Was Submitted Successfully!!</h1>

        {% else %}

       
            
            <form action="" method=POST enctype="multipart/form-data">
                {% csrf_token %}

                {{ form.as_p }}


                <br/>
                <input type="submit" value="Submit" class="btn btn-success">
            <form>
            
        
        {% endif %}
    </center>
   
{% else %}

     <h1>Sorry you must be logined </h1>

    <a href="{% url 'login_user'%}">Login</a>

{% endif %}
 
   
   
    
{% endblock %}

step1/templates/step1/admin_approval.html
{% extends 'step1/layout.html' %}



{% block body %}





    <h1>Admin Dashboard</h1>


    <form action="" method=POST>

        {% csrf_token %}


<div class="card">
  <div class="card-body">
    Event Count: {{ event_count }}<br/>
    Venue Count: {{ venue_count }}<br/>
    User Count:  {{ user_count }}<br/>
  </div>
</div>





<br/><br/>
<h1>Event Approvel</h1>
<br/>




            <table class="table table-striped table-hover table-bordered">
            <thead>
                <tr>
                <th scope="col">Event Name</th>
                <th scope="col">Approved</th>
                </tr>
            </thead>
            <tbody>
            {% for event in event_list %}
            <tr>
                <td>{{ event }} <br/></td>
                <td>
                    {% if event.approved %}
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" checked="checked" value={{ event.id}} name="boxes">
                        </div>


                    {% else %}   


                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" value={{ event.id}} name="boxes">
                        </div>



                    {% endif %}
                
                </td>
                </tr>

                
                
                {% endfor %}

                        
                
                </tbody>
                
                
                
                
<br/>


 


<button class='btn btn-secondary' type="submit">
    update 
</button>


<br/>

{% endblock %}

step1/templates/step1/event_list.html
{% extends 'step1/layout.html' %}



{% block body %}



<br>

{% for event in event_list %}

{% if event.approved %}

    <div class="card">
    <div class="card-header">
        {{ event }}
    </div>
    <div class="card-body">
        <h5 class="card-title">{{ event.venue }}</h5>

        <p class="card-text"> 
        
        
        

                

                <ul>
                    <li> <b>Date:</b> {{ event.event_date }} </li>
                    <li> <b>Days Till Event:</b> {{ event.Days_till }}</li>                    <li> <b>Venue:</b> {{ event.venue }} </li>
                    <li> <b>Manager:</b> {{ event.manager }} </li>
                    <li> <b>Description:</b> {{ event.description }} </li>
                    <li><b>Approved:</b> {{ event.approved }}</li>

                    {% for user in event.attendees.all %}
                        <li> <b>Attendees:</b> {{ user }} </li>
                    {% endfor%}
            </ul>
            
        
        </p>


        {% if user.is_authenticated %}

            {% if user == event.manager %}




                <div class="card-footer text-body-secondary">
                    <a href="{% url 'step1:update_event' event.id %}" class="btn btn-outline-secondary btn-sm">update</a>

                    <a href="{% url 'step1:delete_event' event.id %}" class="btn btn-outline-danger btn-sm">delete</a>

                </div>
            
            {% endif %}



        {% endif %}



    </div>
    </div>


<br>

{% endif %}
   
{% endfor %}
 
   
   
    
{% endblock %}

step1/templates/step1/index.html
{% extends 'step1/layout.html' %}



{% block body %}



<h1>The month is {{ month }} and the month number is {{ month_number }}of {{ year }}</h1>

    <center>{{ cal|safe }}</center>

    <br/><br/>
<center>

    <h3>Events This Months</h3>

    {% if event_list %}

        {% for event in event_list %}
            {{ event }} - {{event.event_date}}<br/>
        {% endfor %}

    {% else %}

        sorry there is no events

    {% endif %}


</center>



{% endblock %}

step1/templates/step1/my_events.html
{% extends 'step1/layout.html' %}



{% block body %}



    <h2>My Events</h2>
    <br/>
        

        {% for event in events %}
            {{ event.name }}<br/>
        {% endfor %}

    
{% endblock %}

step1/templates/step1/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'step1:index' %}">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

       <li class="nav-item">
          <a class="nav-link" href="{% url 'step1:event_list'%}">Event_list</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'step1:list_venue'%}">venue</a>
        </li>
 <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            ADD
          </a>




         <ul class="dropdown-menu">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'step1:add_venue'%}">ADD Venue</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'step1:add_event'%}">ADD Event</a>
            </li>


           <li class="nav-item">
              <a class="nav-link" href="{% url 'step1:my_events'%}">My Event</a>
            </li>

          </ul>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Download
          </a>

         <ul class="dropdown-menu">
             <li class="nav-item">
              <a class="dropdown-item" href="{% url 'step1:venue_text'%}">Venue_Text</a>
            </li>
            <li class="nav-item">
              <a class="dropdown-item" href="{% url 'step1:venue_csv'%}">Venue_CSV</a>
            </li>
          

            <li class="nav-item">
              <a class="dropdown-item" href="{% url 'step1:venue_pdf'%}">Venue_pdf</a>
            </li>

             



          </ul>

      


      {% if user.is_authenticated %}


         <li class="nav-item">
          <a class="nav-link" href="{% url 'logout_user'%}">logout</a>
        </li>



      {% else %}




        <li class="nav-item">
          <a class="nav-link" href="{% url 'register_user' %}">Register</a>
        </li>
       



        <li class="nav-item">
          <a class="nav-link" href="{% url 'login_user'%}">login</a>
        </li>
       
    

      {% endif %}

      <li class="nav-item">
          <a class="nav-link" href="{% url 'step1:search_events'%}">search_events</a>
        </li>


      {% if user.is_superuser %}

        <li class="nav-item">
          <a class="nav-link" href="{% url 'step1:admin_approvel' %}">Admin Approvel</a>
        </li>



      {% endif %}


      </ul>


      <form class="d-flex" method=POST action="{% url 'step1:search_venues'%}" > 
      
      
      
        {% csrf_token %}

          
          
          <input class="form-control me-2" type="search" placeholder="Search Venue" aria-label="Search" name="searched">
          <button class="btn btn-outline-secondary" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

step1/templates/step1/search_events.html
{% extends 'step1/layout.html' %}



{% block body %}

 <h1>You Searched For {{ searched }} </h1>

<br/>

 <div class="card">
     <div class="card-header">
         {{ event }}
        </div>
                            
    <div class="card-body">
  

     <form method=POST action="{% url 'step1:search_events'%}" > 
      
      
      
        {% csrf_token %}

          
          
          <input class="form-control me-2" type="search" placeholder="Search Events" aria-label="Search" name="searched"><br/>
          <button class="btn btn-outline-secondary" type="submit">Search</button>
      </form>
    </div>
    </div>

            {% if searched %}
            
            <br/>
               
                

                {% for event in events %}

                 
                        <div class="card">
                                <div class="card-header">
                                        {{ event }}
                                </div>
                            
                                <div class="card-body">
                                    <h5 class="card-title">{{ event.venue }}</h5>

                                        <p class="card-text"> 
                                        
                                        
                                        

                                                

                                            <ul>
                                                    <li> <b>Date:</b> {{ event.event_date }} </li>
                                                    <li> <b>Venue:</b> {{ event.venue }} </li>
                                                    <li> <b>Manager:</b> {{ event.manager }} </li>
                                                    <li> <b>Description:</b> {{ event.description }} </li>

                                                    {% for user in event.attendees.all %}
                                                        <li> <b>Attendees:</b> {{ user }} </li>
                                                    {% endfor%}
                                                
                                            </ul>
                                            
                                        
                                        </p>
                                       

                                    
                                </div>
                        </div>
                        <br/>
                             
                       
            
                {% endfor %}

            {% else %}

                <h1>Hey! You Forgot To Search For A Venue </h1>

            {% endif %}


     
<br/> 

{% endblock %}

step1/templates/step1/search_venues.html
{% extends 'step1/layout.html' %}



{% block body %}


    <center>

        {% if searched %}
        

            <h1>You Searched For {{ searched }} </h1>
            <br/>

            {% for venue in Venues %}
                    <a href="{% url 'step1:show_venue' venue.id %}"> {{ venue }}</a><br/>

            {% endfor %}

        {% else %}

            <h1>Hey! You Forgot To Search For A Venue </h1>

        {% endif %}
        
    </center>

{% endblock %}

step1/templates/step1/venues.html
{% extends 'step1/layout.html' %}



{% block body %}

<center>

    <h1>Venues...</h1>
    <br/>

    <table class="table table-striped table-hover">


        {% for venue in venues %} 

            <tr>
                <td> 
                
                    <a href= "{% url 'step1:show_venue' venue.id %}"> {{ venue }} </a><br/>
                
                </td>
                <td align="right">

                   {% if user.is_authenticated %}
                   
                        <a href="{% url 'step1:update_venue' venue.id %}" class="btn btn-outline-secondary btn-sm">update</a>
                        <a href="{% url 'step1:delete_venue' venue.id %}" class="btn btn-outline-danger btn-sm">Delete</a>
                    

                   {% endif %} 



                </td>

                
            </tr>
        {% endfor %} 
    
    </table>

    </center>
<!--
    <br/><br/>
    {{ venues }}<br/>

    Has Previous: {{ venues.has_previous }} <br/>
    Has Next: {{ venues.has_next }}<br/>
    Number of Page: {{ venues.paginator.num_pages }}<br/>
    Current: {{ venues.number }}
    <hr><br/><br/> 

-->


<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
   




    {% if venues.has_previous %}


        <li class="page-item"><a class="page-link" href="?page=1">&laquo First</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ venues.previous_page_number }}"> previous </a></li>



    {% endif %}


   <!-- <li class="page-item"><a class="page-link" href="#">page {{ venues.number }} of {{ venues.paginator.num_pages }}</a></li>-->

{% for i in nums %}

     <li class="page-item"><a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>


{% endfor %}


    {% if venues.has_next %}


        <li class="page-item"><a class="page-link" href="?page={{ venues.next_page_number }}"> Next </a></li>
        <li class="page-item"><a class="page-link" href="?page={{ venues.paginator.num_pages }}">Last &raquo </a></li>


    {% endif %}

  </ul>
</nav>


{% endblock %}